### ISSUE TITLE
Other loss than triplet loss

### ISSUE THREAD

**Issue by duhyunkim1** [SikaStar/IDM#16]
Hi, Thank you for your great work.

Was there a particular reason for applying triplet loss on source and target domains' features?
I was just wondering whether you have applied contrastive loss rather than triplet loss.

Would it also work on your network?

Thanks in advance.!

**Comment by SikaStar** [comment]
> Hi, Thank you for your great work.
> 
> Was there a particular reason for applying triplet loss on source and target domains' features? I was just wondering whether you have applied contrastive loss rather than triplet loss.
> 
> Would it also work on your network?
> 
> Thanks in advance.!

Hi,

The reason for applying the triplet loss on these features is that triplet loss has been widely used in ReID. You can refer to some common implementations like https://github.com/JDAI-CV/fast-reid, https://github.com/michuanhaohao/reid-strong-baseline.

As far as I know, the contrastive loss performs worse than the triplet loss in ReID. Until now, combining the classification loss and the triplet loss is still dominant in ReID.

Replacing the triplet loss with the contrastive loss can also work because our proposed IDM module dose not depend on the specific form of the loss.

**Comment by duhyunkim1** [comment]
Thank you!!! 
I have one more question.

 

I figured out that you did not apply triplet or CE loss to the intermediate feature,
although there are labels.

 

Is there no point applying triplet loss
to pull feature close to each other or push other label feature far away 
in the intermediate domain?

**Comment by SikaStar** [comment]
> Thank you!!! I have one more question.
> 
> I figured out that you did not apply triplet or CE loss to the intermediate feature, although there are labels.
> 
> Is there no point applying triplet loss to pull feature close to each other or push other label feature far away in the intermediate domain?

The labels corresponding to generated intermediate features are mixed by a source label and a target pseudo label. It is hard to distinguish the identity which generated features belong to. What's more important is that the generated intermediate domains are used to better align the source and target domains instead of making intermediate features more discriminative.
